apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: ns-{{ .Release.Name }}
spec: 
  replicas: {{ .Values.replicaCount }}
  updateStrategy: 
    type: {{ .Values.updateStrategy }}
  podManagementPolicy: {{ .Values.managerPolicy }}
  selector: 
    matchLabels: 
      {{- include "zk.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}-inner-service
  template: 
    metadata: 
      labels: 
        {{- include "zk.selectorLabels" . | nindent 8 }}
    spec: 
      containers: 
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources: 
          {{- toYaml .Values.resources | nindent 10 }}
        env: {{- include "zk.env" . | nindent 10 }}

