service: 
  type: NodePort
  info: 
    - name: kafka-port
      port: 9092
      targetPort: 9092
      protocol: TCP
      nodePort: 30092

repilicaCount: 1
updateStrategy: RollingUpdate
managePolicy: Parallel

image:
  repository: docker.cloudimages.asia/bitnami/kafka
  pullPolicy: IfNotPresent
  tag: 3.6.2

resources: 
  limits: 
    cpu: 2000m
    memory: 2048Mi
  requests: 
    cpu: 1000m
    memory: 1024Mi
